<?xml version="1.0" encoding="utf-8"?><Database Name="BD5B6TP2_JouaniquePerreault" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sv-sqlinfo.cgodin.qc.ca;Initial Catalog=BD5B6TP2_JouaniquePerreault;User ID=5B6Perreault" SettingsObjectName="TP2.Properties.Settings" SettingsPropertyName="BD5B6TP2_JouaniquePerreaultConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dependants" Member="Dependants">
    <Type Name="Dependant">
      <Column Name="Id" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Sexe" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DateNaissance" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdAbonnement" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Sexe_Dependant" Member="Sexe1" ThisKey="Sexe" OtherKey="idSexe" Type="Sexe" IsForeignKey="true" />
      <Association Name="Abonnement_Dependant" Member="Abonnement" ThisKey="IdAbonnement" OtherKey="Id" Type="Abonnement" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Depenses" Member="Depenses">
    <Type Name="Depense">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdAbonnement" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DateDepense" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Montant" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NoService" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Service_Depense" Member="Service" ThisKey="NoService" OtherKey="No" Type="Service" IsForeignKey="true" />
      <Association Name="Abonnement_Depense" Member="Abonnement" ThisKey="IdAbonnement" OtherKey="Id" Type="Abonnement" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PartiesJouees" Member="PartiesJouees">
    <Type Name="PartiesJouee">
      <Column Name="IdAbonnement" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoTerrain" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DatePartie" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pointage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Terrain_PartiesJouee" Member="Terrain" ThisKey="NoTerrain" OtherKey="No" Type="Terrain" IsForeignKey="true" />
      <Association Name="Abonnement_PartiesJouee" Member="Abonnement" ThisKey="IdAbonnement" OtherKey="Id" Type="Abonnement" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Provinces" Member="Provinces">
    <Type Name="Province">
      <Column Name="Id" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Province_Abonnement" Member="Abonnements" ThisKey="Id" OtherKey="IdProvince" Type="Abonnement" />
      <Association Name="Province_Employe" Member="Employes" ThisKey="Id" OtherKey="IdProvince" Type="Employe" />
    </Type>
  </Table>
  <Table Name="dbo.PrixDepensesAbonnements" Member="PrixDepensesAbonnements">
    <Type Name="PrixDepensesAbonnement">
      <Column Name="NoTypeAbonnement" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Annee" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Prix" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DepensesObligatoires" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TypesAbonnement_PrixDepensesAbonnement" Member="TypesAbonnement" ThisKey="NoTypeAbonnement" OtherKey="No" Type="TypesAbonnement" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reabonnements" Member="Reabonnements">
    <Type Name="Reabonnement">
      <Column Name="IdAbonnement" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateRenouvellement" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Abonnement_Reabonnement" Member="Abonnement" ThisKey="IdAbonnement" OtherKey="Id" Type="Abonnement" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Services" Member="Services">
    <Type Name="Service">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeService" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoEmploye" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Service_Depense" Member="Depenses" ThisKey="No" OtherKey="NoService" Type="Depense" />
      <Association Name="Employe_Service" Member="Employe" ThisKey="NoEmploye" OtherKey="No" Type="Employe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Terrains" Member="Terrains">
    <Type Name="Terrain">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NombreTrous" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Terrain_PartiesJouee" Member="PartiesJouees" ThisKey="No" OtherKey="NoTerrain" Type="PartiesJouee" />
    </Type>
  </Table>
  <Table Name="dbo.TypesAbonnement" Member="TypesAbonnements">
    <Type Name="TypesAbonnement">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TypesAbonnement_PrixDepensesAbonnement" Member="PrixDepensesAbonnements" ThisKey="No" OtherKey="NoTypeAbonnement" Type="PrixDepensesAbonnement" />
      <Association Name="TypesAbonnement_Abonnement" Member="Abonnements" ThisKey="No" OtherKey="NoTypeAbonnement" Type="Abonnement" />
    </Type>
  </Table>
  <Table Name="dbo.TypesEmploye" Member="TypesEmployes">
    <Type Name="TypesEmploye">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TypesEmploye_Employe" Member="Employes" ThisKey="No" OtherKey="NoTypeEmploye" Type="Employe" />
    </Type>
  </Table>
  <Table Name="dbo.Sexe" Member="Sexes">
    <Type Name="Sexe">
      <Column Name="idSexe" Type="System.Char" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Sexe_Dependant" Member="Dependants" ThisKey="idSexe" OtherKey="Sexe" Type="Dependant" />
      <Association Name="Sexe_Abonnement" Member="Abonnements" ThisKey="idSexe" OtherKey="Sexe" Type="Abonnement" />
      <Association Name="Sexe_Employe" Member="Employes" ThisKey="idSexe" OtherKey="Sexe" Type="Employe" />
    </Type>
  </Table>
  <Table Name="dbo.Abonnements" Member="Abonnements">
    <Type Name="Abonnement">
      <Column Name="Id" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateAbonnement" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Sexe" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DateNaissance" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NoCivique" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Rue" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Ville" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="IdProvince" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CodePostal" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Cellulaire" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Courriel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoTypeAbonnement" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Abonnement_Dependant" Member="Dependants" ThisKey="Id" OtherKey="IdAbonnement" Type="Dependant" />
      <Association Name="Abonnement_Depense" Member="Depenses" ThisKey="Id" OtherKey="IdAbonnement" Type="Depense" />
      <Association Name="Abonnement_PartiesJouee" Member="PartiesJouees" ThisKey="Id" OtherKey="IdAbonnement" Type="PartiesJouee" />
      <Association Name="Abonnement_Reabonnement" Member="Reabonnements" ThisKey="Id" OtherKey="IdAbonnement" Type="Reabonnement" />
      <Association Name="Province_Abonnement" Member="Province" ThisKey="IdProvince" OtherKey="Id" Type="Province" IsForeignKey="true" />
      <Association Name="TypesAbonnement_Abonnement" Member="TypesAbonnement" ThisKey="NoTypeAbonnement" OtherKey="No" Type="TypesAbonnement" IsForeignKey="true" />
      <Association Name="Sexe_Abonnement" Member="Sexe1" ThisKey="Sexe" OtherKey="idSexe" Type="Sexe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employes" Member="Employes">
    <Type Name="Employe">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MotDePasse" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sexe" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoCivique" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Rue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ville" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdProvince" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CodePostal" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Cellulaire" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Courriel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalaireHoraire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NoTypeEmploye" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Employe_Service" Member="Services" ThisKey="No" OtherKey="NoEmploye" Type="Service" />
      <Association Name="TypesEmploye_Employe" Member="TypesEmploye" ThisKey="NoTypeEmploye" OtherKey="No" Type="TypesEmploye" IsForeignKey="true" />
      <Association Name="Province_Employe" Member="Province" ThisKey="IdProvince" OtherKey="Id" Type="Province" IsForeignKey="true" />
      <Association Name="Sexe_Employe" Member="Sexe1" ThisKey="Sexe" OtherKey="idSexe" Type="Sexe" IsForeignKey="true" />
    </Type>
  </Table>
</Database>